# processor-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  attributes:
    actions:
      - key: processor.layer
        action: insert
        value: "true"
  filter:
    error_mode: ignore
    traces:
      span:
        - 'resource.attributes["environment"] == "dev"'
  batch: {}

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes, filter, batch]
      exporters: [debug]