{{- if .Values.processor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-dynamic-processors.processor.fullname" . }}
  labels:
    {{- include "otel-dynamic-processors.processor.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.processor.autoscaling.enabled }}
  replicas: {{ .Values.processor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otel-dynamic-processors.processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/processor-configmap.yaml") . | sha256sum }}
        {{- with .Values.processor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "otel-dynamic-processors.processor.selectorLabels" . | nindent 8 }}
        {{- with .Values.processor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otel-dynamic-processors.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.processor.podSecurityContext | nindent 8 }}
      containers:
        - name: otel-processor
          securityContext:
            {{- toYaml .Values.processor.securityContext | nindent 12 }}
          image: {{ include "otel-dynamic-processors.processor.image" . }}
          imagePullPolicy: {{ .Values.processor.image.pullPolicy }}
          args:
            - --config=/etc/otelcol-contrib/config.yaml
          ports:
            - name: otlp-grpc
              containerPort: {{ index .Values.processor.service.ports "otlp-grpc" }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ index .Values.processor.service.ports "otlp-http" }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.processor.service.ports.metrics }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.processor.service.ports.health }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.processor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.processor.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.processor.resources | nindent 12 }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBE_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_NAME
              value: {{ .Values.application.name }}
            - name: APP_VERSION
              value: {{ .Values.application.version }}
            - name: ENVIRONMENT
              value: {{ .Values.application.environment }}
            - name: SERVICE_NAMESPACE
              value: {{ .Values.application.namespace }}
            - name: CLUSTER_NAME
              value: {{ .Values.application.cluster }}
            - name: REGION
              value: {{ .Values.application.region }}
            - name: LOGS_LEVEL
              value: "info"
            {{- if .Values.grafanaCloud.enabled }}
            - name: GRAFANA_CLOUD_INSTANCE_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafanaCloud.tempo.auth.existingSecret }}
                  key: {{ .Values.grafanaCloud.tempo.auth.instanceIdKey }}
            - name: GRAFANA_CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafanaCloud.tempo.auth.existingSecret }}
                  key: {{ .Values.grafanaCloud.tempo.auth.apiKeyKey }}
            - name: GRAFANA_CLOUD_TEMPO_URL
              value: {{ .Values.grafanaCloud.tempo.endpoint }}
            - name: GRAFANA_CLOUD_PROMETHEUS_URL
              value: {{ .Values.grafanaCloud.prometheus.endpoint }}
            {{- if .Values.grafanaCloud.loki.enabled }}
            - name: GRAFANA_CLOUD_LOKI_URL
              value: {{ .Values.grafanaCloud.loki.endpoint }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /tmp
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "otel-dynamic-processors.processor.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "otel-dynamic-processors.processor.fullname" . }}-data
        {{- end }}
      {{- with .Values.processor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.processor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.processor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}